### ISSUE TITLE
What is issus for the android 9/pie avd?

### ISSUE THREAD

**Issue by cecini** [shakalaca/MagiskOnEmulator#11]
Look at the README.md, exclude the api 28 ,why?

**Comment by fusionneur** [comment]
the code doesn't seem to deny it so i suppose you could give it a try.. i don't know the exact reason why readme specifies this

**Comment by cecini** [comment]
In fact, i try it on an aosp image, and fail. So ask this issue. Have not try it on offical avd image.

**Comment by cecini** [comment]
In Pr https://github.com/topjohnwu/Magisk/pull/2594, shakalaca said andorid 28 use SAR(system as root), so the ramdisk have merged in to the system.img. So how to fix this ?

**Comment by shakalaca** [comment]
API 28 uses system.img as boot.img (root / ramdisk) , when kernel boots up, it then quickly loads ramdisk in system.img, so there's no simple way to patch neither kernel (not possible in binary form) nor system.img (too big)

The only and easy way to fix this is using custom kernel, but I have no idea how to do it automatically.
