### ISSUE TITLE
unzip: short read when patching with canary

### ISSUE THREAD

**Issue by fusionneur** [shakalaca/MagiskOnEmulator#13]
Bug occured randomly when trying to patch Android 11/R x86 with latest canary magisk via powershell script.
It looks like magisk zip is downloaded corrupted sometimes.

MagiskOnEmulator> .\patch.bat canary
ramdisk.img: 1 file pushed, 0 skipped. 114.0 MB/s (1476700 bytes in 0.012s)
magisk_emu.zip: 1 file pushed, 0 skipped. 145.4 MB/s (12863269 bytes in 0.084s)
update-binary: 1 file pushed, 0 skipped. 51.2 MB/s (3527756 bytes in 0.066s)
process.sh: 1 file pushed, 0 skipped. 2.9 MB/s (5782 bytes in 0.002s)
[*] Extracting busybox ..
[*] Checking Android version
[*] Fetching canary version of Magisk ..
Connecting to raw.githubusercontent.com (151.101.0.133:443)
wget: note: TLS certificate validation not implemented
saving to 'magisk.zip'
magisk.zip             0% |                                | 12339  0:16:07 ETA
magisk.zip             6% |**                              |  786k  0:00:27 ETA
magisk.zip            10% |***                             | 1218k  0:00:25 ETA
magisk.zip            17% |*****                           | 2018k  0:00:19 ETA
magisk.zip            29% |*********                       | 3378k  0:00:12 ETA
magisk.zip            46% |**************                  | 5362k  0:00:06 ETA
magisk.zip            67% |*********************           | 7810k  0:00:03 ETA
magisk.zip            93% |******************************  | 10.6M  0:00:00 ETA
magisk.zip           100% |********************************| 11.3M  0:00:00 ETA
'magisk.zip' saved
wget: got bad TLS record (len:30) while expecting encrypted data
 03 03 00 1a 22 29 91 9e 31 e2 68 b6 35 c7 33 08 32 f8 10 d8 6b 42 2b bb 6f 9d 95 2c ff 72
[-] API level greater then 30
[*] Check if we need to repack ramdisk before patching ..
[-] Multiple cpio archives detected
[*] Unpacking ramdisk ..
[-] Dumping from 0 to 2184316 ..
[-] Dumping from 2184448 to 4310644 ..
[*] Repacking ramdisk ..
[*] Unzipping Magisk ..
unzip: short read
mv: bad '/data/local/tmp/tmp/x86/*': No such file or directory
mv: bad '/data/local/tmp/tmp/common/*': No such file or directory
mv: bad '/data/local/tmp/tmp/chromeos': No such file or directory
[*] Checking ramdisk status ..
/data/local/tmp/process.sh[123]: /data/local/tmp/magisk/magiskinit: inaccessible or not found
[*] Patching ramdisk ..

[*] Done patching, compressing ramdisk ..
/data/local/tmp/process.sh[148]: /data/local/tmp/magisk/magiskboot: inaccessible or not found
/data/local/tmp/process.sh[152]: /data/local/tmp/magisk/magiskboot: inaccessible or not found
/data/local/tmp/process.sh[153]: /data/local/tmp/magisk/magiskboot: inaccessible or not found
/data/local/tmp/process.sh[154]: /data/local/tmp/magisk/magiskboot: inaccessible or not found
[*] Installing MagiskManager ..
Error: Unable to open file: /data/local/tmp/magisk/magisk.apk
Error: Can't open file: /data/local/tmp/magisk/magisk.apk

Exception occurred while executing 'install':
java.lang.IllegalArgumentException: Error: Can't open file: /data/local/tmp/magisk/magisk.apk
        at com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:519)
        at com.android.server.pm.PackageManagerShellCommand.doRunInstall(PackageManagerShellCommand.java:1282)
        at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:1248)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:184)
        at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
        at android.os.ShellCommand.exec(ShellCommand.java:44)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21605)
        at android.os.Binder.shellCommand(Binder.java:929)
        at android.os.Binder.onTransact(Binder.java:813)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4603)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4306)
        at android.os.Binder.execTransactInternal(Binder.java:1159)
        at android.os.Binder.execTransact(Binder.java:1123)
[*] Installing su binaries ..
[*] Clean up
run-as: unknown package: com.topjohnwu.magisk
/data/local/tmp/ramdisk.img: 1 file pulled, 0 skipped. 14.1 MB/s (1468412 bytes in 0.099s)

**Comment by shakalaca** [comment]
oops, how could we detect this kind of error .. :(
