### ISSUE TITLE
Mounting R/W Android 10+

### ISSUE THREAD

**Issue by fnazal18** [shakalaca/MagiskOnEmulator#14]
Greetings. 

The title is pretty self-explanatory. Although I was able to install Magisk on an emulator based on Android 11 (R), I'm unable to mount system as R/W. 
Is there a way to mount it from the Magisk process itself? Or is it expected to be done by using adb remount / disable-verity command, which is by the way broken in Android 11 Emulators (Get freezed after reboot). 

I appreciate your replies. 

Best regards!

**Comment by yswtrue** [comment]
same issue

**Comment by fusionneur** [comment]
I don't think this is related to the actual implementation of rooting the emulator, but rather more magisk specific. As far as I remember starting from Android 10, you cannot directly remount as R/W the system partition as it is locked to read only. To alter files (delete/modify) on system partition, you would have to do that systemlessly with a magisk module.

REF: https://github.com/topjohnwu/Magisk/issues/1729

Yoy may close this issue as it is out of scope. Thank you
