### ISSUE TITLE
Small doubt

### ISSUE THREAD

**Issue by HemanthJabalpuri** [shakalaca/MagiskOnEmulator#18]
@shakalaca

Thanks for this.
I have just installed lastest canary in 4.4.2 Emulator. Seems like root working fine.

I have a small doubt in script i.e., https://github.com/shakalaca/MagiskOnEmulator/blob/b25497027e7cd11c379547471520bf0c5f2539a5/process.sh#L165-L172

Why it is needed?
Also why the script does not copy files to /data/adb/magisk?

Thanks again.

**Comment by HemanthJabalpuri** [comment]
Also is it possible to install Magisk app players like MEmu, Nox, LDPlayer, BlueStacks?
I can able to get root access from https://github.com/topjohnwu/Magisk/blob/v21.2/scripts/emulator.sh but what about modules?

Thanks

**Comment by RaXorX** [comment]
@HemanthJabalpuri Also is it possible to install Magisk in App Players like MEmu, Nox, LDPlayer, BlueStacks?
I tried installing it on Bluestacks. Everything goes fine except for that run-as command only.
`run-as: Could not set capabilities: Operation not permitted`
This is the error I get at that point, I still get a file pulled but trying to run bluestack with the patched ramdisk.img ends up in an error. It never starts. I guess you've already done that much and found out yourself too.

**Comment by HemanthJabalpuri** [comment]
> I tried installing it on Bluestacks. Everything goes fine except for that run-as command only.
run-as: Could not set capabilities: Operation not permitted
This is the error I get at that point, I still get a file pulled but trying to run bluestack with the patched ramdisk.img ends up in an error. It never starts. I guess you've already done that much and found out yourself too.

Can we able to extract ramdisk.img from bluestacks? Where it is located?

I asked above question because only debug build of Magisk Manager are used. What should we do if we want to set main release.

**Comment by HemanthJabalpuri** [comment]
I have used this script https://github.com/HemanthJabalpuri/Replace_KingRoot_with_SuperSU/blob/master/magisk-boot.sh to root MEmu and it worked.

But if I root BlueStacks in that way, it freezes and does not respond at all. I have to restart BlueStacks to do any operation after the script execution.

**Comment by shakalaca** [comment]
> @shakalaca
> 
> Thanks for this.
> I have just installed lastest canary in 4.4.2 Emulator. Seems like root working fine.
> 
> I have a small doubt in script i.e.,
> 
> https://github.com/shakalaca/MagiskOnEmulator/blob/b25497027e7cd11c379547471520bf0c5f2539a5/process.sh#L165-L172
> 
> Why it is needed?
> Also why the script does not copy files to /data/adb/magisk?
> 
> Thanks again.

without root permission we can not copy files to /data/adb/magisk, the only way to do it is booting with patched ramdisk and "update" those files by MagiskManager (the standard behavior when patching boot.img)

**Comment by HemanthJabalpuri** [comment]
Thanks for the answer but what about copying those files to INSTALL_PATH? Why it is needed? Because of those copying with run-as I cannot able to install main releases instead of canary(since they are not debug).

> without root permission we can not copy files to /data/adb/magisk, the only way to do it is booting with patched ramdisk and "update" those files by MagiskManager (the standard behavior when patching boot.img)

We can able to get root with `adb root` or `ALT + F1` right?
