### ISSUE TITLE
Android S support

### ISSUE THREAD

**Issue by yujincheng08** [shakalaca/MagiskOnEmulator#20]
The `ramdisk.img` format is changed to lz4 in Legacy format (Linux kernel compression).

I tried and successfully patched it. However, Magisk is loaded but caused bootloop.

**Comment by shakalaca** [comment]
I'll look into it later today :)

**Comment by shakalaca** [comment]
Please try the latest commit :)

**Comment by yujincheng08** [comment]
great! You compiled your own magisk right?

I contacted Jhon Wu and he said he didn't want to support pure 64-bit env. But anyway let me try it out!

**Comment by yujincheng08** [comment]
Tested. Works like a charm.

**Comment by yujincheng08** [comment]
seems to have some problem: `/data/adb/magisk`  is empty.

**Comment by KieronQuinn** [comment]
You can fix this manually for the time being:

- Extract magisk_emu.zip in the cloned folder
- Rename all the files in lib/x86 to remove the "lib" and "so" (they're in that format to avoid being mangled by aapt):
![Like this](https://i.imgur.com/uzjYIIp.png)
- Push the files in lib/x86 to /data/adb/magisk and set them to chmod 755
- Push the files in assets to /data/adb/magisk and set them to chmod 755 (I did the files in chromeos too but don't think they're needed)
- Cold reboot the emulator

![Works!](https://i.imgur.com/VZrwt3h.png)

**Comment by yujincheng08** [comment]
Yes I have fixed it manually. But I think it could be done automatically?

BTW, I think you should also submit the code which fixes the manager crash in pure 64 bit env to ur pr in magisk

**Comment by KieronQuinn** [comment]
Yeah it should be done automatically, I think Magisk Manager would be able to fix itself if it detected root but it doesn't.

**Comment by shakalaca** [comment]
Hi everyone, this should be done in the latest commit, would you please verify with new VM setup ? :)
(I'm using Magisk Canary 22001)

**Comment by yujincheng08** [comment]
works! even on M1!
