### ISSUE TITLE
What is binary in update-binary

### ISSUE THREAD

**Issue by soft391** [shakalaca/MagiskOnEmulator#22]
Hi, update-binary has a blob in it. Is this the busybox binary? If so what version and where does it come from? One shouldn't run code like this without knowing what it does.

**Comment by shakalaca** [comment]
The entire update-binary was grab from older Magisk.zip (20307, 72f6770d) and unfortunately John removed the older canary releases on github so I could not get you the origin file. In the mean while if you don't trust me:
1. DO NOT USE
2. Replace the update-binary extracted from here: https://github.com/topjohnwu/magisk_files/blob/f595d0624b70289ed273f933a33075fee986b533/magisk-debug.zip

**Comment by shakalaca** [comment]
Also
