### ISSUE TITLE
Problem after installation on Android x86 8.1 VirtualBox

### ISSUE THREAD

**Issue by justneedhelp** [shakalaca/MagiskOnEmulator#23]
Hi. I installed Magisk v.21.4 successfully using the steps provided in description but after installation I have this error in Magisk Log. I don't know how to solve that. Please help! Thank you!
![MagiskError](https://user-images.githubusercontent.com/79741381/109419612-a564c280-79ce-11eb-84af-b87988bd041e.png)

**Comment by justneedhelp** [comment]
Hm... it seems I found the reason of this problem (assuming I use Android x86 8.1.0 VirtualBox):
Output `cat /proc/mounts` shows me the following output:
![bug](https://user-images.githubusercontent.com/79741381/109425558-12855180-79e9-11eb-8065-8c29a847592c.png)
So, the devices are becoming busy after Android has booted so Magisk cannot remount them. I think you should modify the init.rc script into the `ramdisk.img` in order to allow Magisk to mount mirrors or something like that. Could you do this? Thank you!

**Comment by justneedhelp** [comment]
I tried all versions of Magisk from 20.4 to 22.0 on Android x86 8.1.0 VirtualBox. Version 20.4 has error log:
`E Magisk  : mount /sbin/.magisk/block/system->/sbin/.magisk/mirror/system failed with 2: No such file or directory`
All the versions of Magisk started from 21.0 had the Issue `16: Device or resourse busy`. I think you fixed the Issue `2: No such file or directory` by commiting https://github.com/topjohnwu/Magisk/pull/2594 but after your commit on April, 2020, no changes in Magisk were made so Magisk Modules on VirtualBox doesn't work at all. Any way to fix  `16: Device or resourse busy` ? Thank you!

**Comment by shakalaca** [comment]
Thanks for your deeply investigation, much appreciate :) I'll take a look once I got time, stay tuned !

**Comment by justneedhelp** [comment]
> Thanks for your deeply investigation, much appreciate :) I'll take a look once I got time, stay tuned !

The only version of Magisk I could successfully use with Modules capability is the latest Magisk Canary on top of Android x86_64 8.1.0 VirtualBox.
With Android x86 7.1.2 VirtualBox, Magisk Modules don't work at all with all versions of Magisk.

**Comment by justneedhelp** [comment]
I noticed a fact that if a device `/dev/block/sda1` (which is /data directory) is mounted to `/sbin/.magisk/mirror/modules` (check this in `/proc/mounts` then modules capability will work well even with error `16: Device or resourse busy`. The only version of Magisk which mounts modules mirror well is the latest canary version with Android x86_64 8.1.0. I'm not good in Android coding so I'm only can debug and test so I think I found the reason of the problem. I hope you will be able to fix it! Thank you!

**Comment by justneedhelp** [comment]
https://github.com/shakalaca/MagiskOnEmulator/issues/24#issuecomment-789832220

**Comment by mcdoe** [comment]
Wait, so you needed to mount data and system in .magisk in init.rc because the manager makes use of this directory at some point? Does the normal version of magisk mount these directories in this same way?

**Comment by shakalaca** [comment]
> Wait, so you needed to mount data and system in .magisk in init.rc because the manager makes use of this directory at some point? Does the normal version of magisk mount these directories in this same way?

Yes, Magisk changed the mount points for various reason:
1. For module adding changes to /system
2. For hiding certain binaries for specific app
3. Maintain the compatibility in different Android versions (whether you're using SAR, A-only, Legacy boot method..)

I'm not sure if initrd patch is still needed but it was required at the time I begin this project. If you're interested you may try to boot VM without patching initrd and see what will happen then. :)

**Comment by shakalaca** [comment]
> I see. By the way, do you know why magisk manager in release 22001 doesn't see magisk?

The app extracts the wrong binary so it couldn't launch the root detection process.
