### ISSUE TITLE
Magisk v22 unable to install

### ISSUE THREAD

**Issue by justneedhelp** [shakalaca/MagiskOnEmulator#24]
Hi. Magisk developers somehow don't want to stay everything on its place, they need to f... break everything and now Magisk Core and Manager are merged into one .apk file. So, Magisk app now cannot work as system app, it shows "Abnormal state" error. I tried to delete Magisk Manager and reinstalled Magisk v22 apk (renamed it to magisk.zip). Your scripts worked fine but after installation I opened Magisk app and see that it shows that Magisk is not installed. Any way to fix it? Thank you!
![MagiskBug](https://user-images.githubusercontent.com/79741381/109421692-a39ffc80-79d8-11eb-99e1-e3613943f811.png)

**Comment by justneedhelp** [comment]
I deleted new Magisk (v22) apk and installed old Magisk Manager v.8.0.7 and I can confirm that using old-stype Magisk Manager, Magisk Core is detected well. So, the problem is in new Magisk installation style, I guess. Are you going to fix it? Thank you!
![MagiskBug1](https://user-images.githubusercontent.com/79741381/109421854-5e2fff00-79d9-11eb-81cf-00a69a078d1d.png)

**Comment by HemanthJabalpuri** [comment]
Is it now working as you said here https://github.com/topjohnwu/Magisk/issues/3760#issuecomment-788172100 ?

Thanks

**Comment by justneedhelp** [comment]
> Is it now working

Yes, modules are working. First time, you need to install module .zip through CLI via `adb shell` then `su` and `#magisk --install-module /path/to/module.zip`. After module successfully installed, reboot the machine and open Magisk Manager. Close 'Abnormal State' error and Magisk will detect Magisk Core.

But now I have another problem. Magisk Canary changed my CPU ABI from `x86_64` to `i686` so some modules cannot be installed. Magisk is so buggy now on Android x86 distributions...

**Comment by newbit1** [comment]
> I deleted new Magisk (v22) apk and installed old Magisk Manager v.8.0.7 and I can confirm that using old-style Magisk Manager, Magisk Core is detected well. So, the problem is in new Magisk installation style, I guess. Are you going to fix it? Thank you!
>

This is not entirely true. Even with the Magisk V22 App installed, and even if it says N/A,
if you execute su in the adb shell, the permission window pops up and you can grant it.
I've noticed that this "additional setup required" is ether missing in V22 or not working proper
in 8.0.7. with the V22 init. Just the updater-binary script remains in /data/adb/magisk directory.
And the  "additional setup required" keeps popping up every time.

So a whole part from the updater-script is missing:
`ui_print "- Constructing environment"`
`rm -rf $MAGISKBIN/* 2>/dev/null`
`mkdir -p $MAGISKBIN 2>/dev/null`
`cp -af $BINDIR/. $COMMONDIR/. $BBBIN $MAGISKBIN`
`chmod -R 755 $MAGISKBIN`

If you do this manually while you are root, Magisk App just shows it right.
Tested on:
[Android 12 (S) API 30 Google Apis Play Store x86_64 r01 Darwin/MacOS Production Build](https://dl.google.com/android/repository/sys-img/google_apis_playstore/x86_64-S_r01-darwin.zip)
<img src="https://user-images.githubusercontent.com/37043777/109728217-0d293200-7bb6-11eb-91d8-15b3a7535a49.png" width="300">
<img src="https://user-images.githubusercontent.com/37043777/109728330-4366b180-7bb6-11eb-88a7-357864bbe647.png" width="300">

BTW: I love the Idea with the fake boot.img, but it didn't work. Hope this will get fixed.

**Comment by justneedhelp** [comment]
> If you do this manually while you are root, Magisk App just shows it right.

Ok. What about Modules functionality? Is it working? I couldn't get modules work neither on Android 8 x86_64 not Android 7 x86 because modules mirror is not mounted. MagiskSu and MagiskHide works fine on every version or Android/Magisk.

**Comment by justneedhelp** [comment]
>  Just the updater-binary script remains in /data/adb/magisk directory

I'm really confused by I don't have any files in `/data/adb/magisk` directory after flashing Magisk on a pure Android x86 7.1.2 VirtualBox.
![confused](https://user-images.githubusercontent.com/79741381/109811184-c9244480-7c2a-11eb-9f81-d4daaa4627fa.png)

**Comment by newbit1** [comment]
I've added this in my script rootAVD, construct_environment(), which only works on AVDs. I guess you have to add it into the patch_vbox.sh script and adjust it to its variables.
I can install modules the normal way, without errors.
I am wondering what happens, If one would call the Magisk App from ADB Shell with su -c and pm.

**Comment by justneedhelp** [comment]
> I am wondering what happens

I just cannot install modules because of "Incomplete environment setup" Magisk error. Not only me, this problem is also related to https://github.com/topjohnwu/Magisk/issues/3760

**Comment by justneedhelp** [comment]
WHOA! I made Magisk Modules work well! The reason of Magisk environment setup error was the following:

1. You MUST use `adb root` before you run scripts from this project and only then type `adb connect 'IP'`! Please update README page!
2. You MUST grab ONLY CANARY version of Magisk in order to install it via this project scripts. Please update README!

The `process.sh` script contains this important string:
`run-as com.topjohnwu.magisk cp -r $MAGISK_DIR/* $INSTALL_PATH`

So ONLY DEBUG version of Magisk apk contains installations files which are copied to installation path. Without them, Modules will NOT work! It was so easy! Tested on Android x86 (32-bit) 7.1.2 VirtualBox.

And yes, I still get Magisk N/A error so I just removed v22 manager via:
`adb uninstall com.topjohnwu.magisk`
And installed Magisk Manager 8.0.7 with ignoring 'Additional setup' pop-up window. We are still waiting that @shakalaca will fix Magisk detection/additional setup error in VirtualBox scripts!

**Comment by mtrss** [comment]
@justneedhelp @newbit1 are you passing safetynet?

**Comment by mcdoe** [comment]
@justneedhelp @newbit1 are either of you passing safetynet?

**Comment by shakalaca** [comment]
Would you please try with latest commit ? Thanks :)

**Comment by newbit1** [comment]
> 
> 
> @justneedhelp @newbit1 are either of you passing safetynet?

No it does not pass the safetynet on AVDs. I've tried a couple of modules,
but only @Didgeridoohan's [MagiskHidePropsConf](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf) was able to get installed.
Also I don't know how to debug the safteynet checks to find out what's the issue in detail.
I've read somewhere that there is a special reason why it can't be done in AVDs,
but can't find the source of this claim right now, sry.

Regarding the Requires Additional Setup Issue on v22:
I've found out, that it pops up on AVDs lower than S and that it get installed proper.
Also, on S it seems there is at least one command blocked from SELINUX that has something to do with Magisk.

**Comment by mcdoe** [comment]
yes I would assume that it can't be done on AVDs. How about genymotion. That seems to be what people use for this. Personally, I am just trying to set up a lab for security testing of android apps, but can't do it if they won't open. @shakalaca any hints?

**Comment by mcdoe** [comment]
By the way, it seems like Google hates emulators, even when used by legitimate security researchers. @shakalaca @newbit1 @justneedhelp @0x5ECF4ULT Let's start a less public email convo. I'm trying to get a solution for this. Email me at mcdoe1@protonmail.com Or even better, lets start the discussion on bloodhoundgang slack channel.  https://bloodhoundgang.herokuapp.com/ This message on this channel disappears after 10 days.
