### ISSUE TITLE
I deleted new Magisk (v22) apk and installed old Magisk Manager v.8.0.7 and I can confirm that using old-style Magisk Manager, Magisk Core is detected well. So, the problem is in new Magisk installation style, I guess. Are you going to fix it? Thank you!

### ISSUE THREAD

**Issue by Rob801130** [shakalaca/MagiskOnEmulator#25]
I deleted new Magisk (v22) apk and installed old Magisk Manager v.8.0.7 and I can confirm that using old-style Magisk Manager, Magisk Core is detected well. So, the problem is in new Magisk installation style, I guess. Are you going to fix it? Thank you!
![MagiskBug1](https://user-images.githubusercontent.com/79741381/109421854-5e2fff00-79d9-11eb-81cf-00a69a078d1d.png)

_Originally posted by @justneedhelp in https://github.com/shakalaca/MagiskOnEmulator/issues/24#issuecomment-787461142_

**Comment by shakalaca** [comment]
What's your environment ?
1. VirtualBox ?
2. Android 7.x, 8.x, 9.x ? x86 or x86_64 ?

For Magisk App issue would you please start a new VM and patch with latest commit ? :)

**Comment by shakalaca** [comment]
Since no further report I'll close this issue
