### ISSUE TITLE
Dynamically update : latest magisk & busybox

### ISSUE THREAD

**Issue by fusionneur** [shakalaca/MagiskOnEmulator#3]
Right now magisk.zip is pre-downloaded. For having latest version would be great to implement a way to dynamically update it by downloading it from official sources. Same applies for busybox.

**Comment by shakalaca** [comment]
Using a pre-downloaded or customized build of magisk.zip prevents the breakage support of x86 in Magisk Canary version. But I think it is good to have an option for people to sync upstream automatically. :)

**Comment by shakalaca** [comment]
Now we can execute ' patch.sh canary ' to use latest canary build :)

https://github.com/shakalaca/MagiskOnEmulator/commit/9fe167a6d8bc8483b032ecf802737d7c197bad9d

**Comment by fusionneur** [comment]
Awesome ! I will test as soon as I can.

**Comment by fusionneur** [comment]
It worked! 

However:
FIRST thought:
It would be good to have the documentation updated so that it is clear for somebody new on how to update magisk after ramdisk was previously already patched:
1. It is mandatory for future magisk updates, to have a backup of the original ramdisk.img that will be used for patching with latest canary ( because only the original ramdisk can be patched . an already patched one fails to be patched again). ---- we could actually backup the ramdisk initially and reuse it in future patching (see below)
2. magisk manager apk can be updated from within the manager itself.

SECOND thought:
A mention about the git commit. I think the patch.sh doesn't need to be modified at all (no need for the "if [[ "$1" != "canary" ]]"), as magisk.zip is removed anyways in process.sh before downloading it from github. Also, patch.bat needs the canary parameter passed: adb -e shell "sh /data/local/tmp/process.sh /data/local/tmp $1"



How the patching scripts could look like:

patch.sh:

#!/bin/sh
adb wait-for-device
if [[ -s ramdisk.img.BACKUP ]]; then
#restore original ramdisk.img for patching
cp -f ramdisk.img.BACKUP ramdisk.img
else
#backup original ramdisk for future patching
cp ramdisk.img ramdisk.img.BACKUP
fi
adb -e push ramdisk.img /data/local/tmp/ramdisk.img.gz
adb -e push magisk_emu.zip /data/local/tmp/magisk.zip
adb -e push update-binary /data/local/tmp/
adb -e push process.sh /data/local/tmp/
adb -e shell "dos2unix /data/local/tmp/process.sh"
adb -e shell "sh /data/local/tmp/process.sh /data/local/tmp $1"
adb -e pull /data/local/tmp/ramdisk.img

_____________________________________________________________________

patch.bat:

@echo off
adb wait-for-device
if exist ramdisk.img.BACKUP (
rem restore original ramdisk.img for patching
copy /b/v/y ramdisk.img.BACKUP ramdisk.img
) else (
rem backup original ramdisk for future patching
copy /b/v/y ramdisk.img ramdisk.img.BACKUP
)
adb -e push ramdisk.img /data/local/tmp/ramdisk.img.gz
adb -e push magisk_emu.zip /data/local/tmp/magisk.zip
adb -e push update-binary /data/local/tmp
adb -e push process.sh /data/local/tmp
adb -e shell "dos2unix /data/local/tmp/process.sh"
adb -e shell "sh /data/local/tmp/process.sh /data/local/tmp $1"
adb -e pull /data/local/tmp/ramdisk.img

**Comment by shakalaca** [comment]
> It worked!
> 
> FIRST thought:
> It would be good to have the documentation updated so that it is clear for somebody new on how to update magisk after ramdisk was previously already patched:
> 
> 1. It is mandatory for future magisk updates, to have a backup of the original ramdisk.img that will be used for patching with latest canary ( because only the original ramdisk can be patched . an already patched one fails to be patched again).
> 2. magisk manager apk can be updated from within the manager itself.
> 
> SECOND thought:
> A mention about the git commit. I think the patch.sh doesn't need to be modified at all (no need for the "if [[ "$1" != "canary" ]]"), as magisk.zip is removed anyways in process.sh before downloading it from github. Also, patch.bat needs the canary parameter passed: adb -e shell "sh /data/local/tmp/process.sh /data/local/tmp $1"

Really appreciate your feedback ! I'll see what I can do, in the mean time it would be great if you can issue a PR ;-)

**Comment by fusionneur** [comment]
#6 Here's the PR
