### ISSUE TITLE
Readme is unclear 

### ISSUE THREAD

**Issue by spartanhooah** [shakalaca/MagiskOnEmulator#34]
I'm trying to follow the readme, but in at least two places I don't understand the directions.
1: Step 0: "Grab Magisk.zip and put in this directory." Grab that zip from where? What is "this directory"?
2: Step 4: "Start the newly created AVD." I don't see a new AVD in the AVD manager. I assume this new AVD isn't created by magic. Could there be some more steps provided please?

**Comment by shakalaca** [comment]
1. This repo
2. create the AVD from AVD manager first

**Comment by spartanhooah** [comment]
1. There is no `Magisk.zip` in this repo, as far as I can tell.
2. Are there any specific requirements of the new AVD?

**Comment by slhck** [comment]
I tried to improve the README in #42

**Comment by 89z** [comment]
Please ignore that pull request, it is invalid.

**Comment by slhck** [comment]
The pull request is certainly valid, however it fixes only the Shell script, not the Batch file.
