### ISSUE TITLE
Support Magisk with 64bit binaries

### ISSUE THREAD

**Issue by yujincheng08** [shakalaca/MagiskOnEmulator#35]
Magisk now contains 64bit binaries in its apk (https://github.com/topjohnwu/Magisk/commit/66cc9bc545585c5d6e5833fdb55964c9b0385f43). But MagiskOnEmulator cannot pick 64bit binaries during installation.

**Comment by shakalaca** [comment]
the latest canary is May 12

**Comment by yujincheng08** [comment]
But we have [CI build](https://github.com/topjohnwu/Magisk/suites/2732097331/artifacts/60318601), which I tested with failure.

**Comment by shakalaca** [comment]
any log ? it works on my machine .. ;-)

**Comment by yujincheng08** [comment]
```
fopen: /data/local/tmp/magisk/magisk32 failed with 2: No such file or directory
Loading cpio: [/data/local/tmp/ramdisk.img]
Add entry [init] (0750)
Create directory [overlay.d] (0750)
Create directory [overlay.d/sbin] (0750)
open: /data/local/tmp/magisk/magisk32.xz failed with 2: No such file or directory
```

But anyway, it works after 2561f3f06d523b038bb7055522cb024b33995f17. Thanks!
