### ISSUE TITLE
Magisk update fails

### ISSUE THREAD

**Issue by fusionneur** [shakalaca/MagiskOnEmulator#5]
Updating the manager apk works fine.
however updating magisk itself (zip) from inside the manager (preserving dm-verity and force encryption) through direct installation fails:

```!Unable` to detect target image
!Installation failed```

is this the supposed behaviour on emulator? How can we update to latest magisk in this case?

**Comment by shakalaca** [comment]
It's the reason why I've created this repo, the manager just cannot patch the ramdisk of emulator directly.

**Comment by fusionneur** [comment]
Understood then. We can link this to #3 in this case and close. Thank you for the explanation.
