### ISSUE TITLE
Magisk 23 apk fails to patch, Android 10 (Q)

### ISSUE THREAD

**Issue by SynapseScribe** [shakalaca/MagiskOnEmulator#51]
I downloaded the apk from https://github.com/topjohnwu/Magisk/releases/tag/v23.0 and copied the ramdisk into the MagiskOnEmulator's folder but it fails detecting the apk. I even renamed the apk into magisk.apk as shown in the error, but i get the same error:

> patch.bat manager OR patch.bat

ramdisk.img: 1 file pushed, 0 skipped. 436.7 MB/s (899609 bytes in 0.002s)
adb: error: cannot stat 'magisk.zip': No such file or directory
busybox: 1 file pushed, 0 skipped. 584.1 MB/s (2074240 bytes in 0.003s)
process.sh: 1 file pushed, 0 skipped. 19.5 MB/s (11934 bytes in 0.001s)

***** Grab magisk.zip or magisk.apk first ! *****

adb: error: failed to stat remote object '/data/local/tmp/ramdisk.img': No such file or directory

**Comment by Daksh777** [comment]
I get the same error on Android S emulator, please let me know if you find a fix.

**Comment by SynapseScribe** [comment]
i ended up downloading magisk zip for v21.4, patching, rebooting and afterwards using patch canary command to upgrade magisk

**Comment by Daksh777** [comment]
Unfortunately, that doesn't work on Android 12 since Magisk v21.4 doesn't support it.
I hope @shakalaca can give an answer if they know a fix for it.

**Comment by CaptainXLAB** [comment]
**You have to rename the extension to zip instead of apk.**
The script (process.sh) looks for **magisk.zip** but you have **magisk.apk**

The error entry from the output:
adb: error: cannot stat 'magisk.zip': No such file or directory

**Comment by SynapseScribe** [comment]
Yep indeed. Figured it out . just an extra note: this is the same as running 'patch.sh/bat canary'. This might be useful for those who need to root without relying on the emulator avd to have internet connectivity as this can be done offline from the avd's perspective. As a matter of fact, the script could be updated to fetch magisk locally and pushing to avd instead of letting the avd download it.

**Comment by SynapseScribe** [comment]
Also as a side note, the documentation should be updated as well to be more intuitive

**Comment by CaptainXLAB** [comment]
@fusionneur Did the patch work for you with Magisk v23?

I tried it using patch.bat, it does patch the ramdisk but that ramdisk doesn't work (manager says not installed). I did find a very long workaround for it and made it work somehow. Just wanting to see if it's just on Android Oreo 8.1 x86 (Google Play) or for other android versions too.

**Comment by SynapseScribe** [comment]
yes, see the comments above
