### ISSUE TITLE
Canary update won't download - patching fails

### ISSUE THREAD

**Issue by fusionneur** [shakalaca/MagiskOnEmulator#8]
Recently i get these TLS related errors when running patch.sh. It fails to properly download the magisk-debug.zip and afterwards the whole process fails:

$ ./patch.sh canary
ramdisk.img: 1 file pushed, 0 skipped. 220.2 MB/s (898859 bytes in 0.004s)
magisk_emu.zip: 1 file pushed, 0 skipped. 367.5 MB/s (12863269 bytes in 0.033s)
update-binary: 1 file pushed, 0 skipped. 353.8 MB/s (3527756 bytes in 0.010s)
process.sh: 1 file pushed, 0 skipped. 4.9 MB/s (5401 bytes in 0.001s)
[*] Extracting busybox ..
[*] Checking Android version
[*] Fetching canary version of Magisk ..
Connecting to raw.githubusercontent.com (151.101.0.133:443)
wget: note: TLS certificate validation not implemented
saving to 'magisk.zip'
magisk.zip            11% |***                             | 1423k  0:00:07 ETA
magisk.zip            23% |*******                         | 2975k  0:00:06 ETA
magisk.zip            44% |**************                  | 5503k  0:00:03 ETA
magisk.zip            79% |*************************       | 9919k  0:00:01 ETA
wget: got bad TLS record (len:53) while expecting encrypted data
 03 03 40 18 7b 3a 8c 47 b4 6a ba 7b 4e 8b 36 7d 14 22 76 58 ad 9a 1e 14 26 0f a5 c9 1b 1a 9f ef 88 07 49 0b ac 0a c4 83 31 0f 2c 2f bd c6 5a c0 66 52 f8 56 1f
wget: connection closed prematurely
[*] Unzipping Magisk ..
unzip: short read
mv: bad '/data/local/tmp/tmp/x86/*': No such file or directory
mv: bad '/data/local/tmp/tmp/common/*': No such file or directory
mv: bad '/data/local/tmp/tmp/chromeos': No such file or directory
[*] Checking ramdisk status ..
/data/local/tmp/process.sh[112]: /data/local/tmp/magisk/magiskinit: inaccessible or not found
[*] Patching ramdisk ..

[*] Done patching, compressing ramdisk ..
/data/local/tmp/process.sh[137]: /data/local/tmp/magisk/magiskboot: inaccessible or not found
/data/local/tmp/process.sh[142]: /data/local/tmp/magisk/magiskboot: inaccessible or not found
/data/local/tmp/process.sh[143]: /data/local/tmp/magisk/magiskboot: inaccessible or not found
[*] Installing MagiskManager ..
Error: Unable to open file: /data/local/tmp/magisk/magisk.apk
Error: Can't open file: /data/local/tmp/magisk/magisk.apk

Exception occurred while executing:
java.lang.IllegalArgumentException: Error: Can't open file: /data/local/tmp/magisk/magisk.apk
        at com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:461)
        at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:1060)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:169)
        at android.os.ShellCommand.exec(ShellCommand.java:104)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21742)
        at android.os.Binder.shellCommand(Binder.java:881)
        at android.os.Binder.onTransact(Binder.java:765)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4860)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4016)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
[*] Installing su binaries ..
[*] Clean up
/data/local/tmp/ramdisk.img: 1 file pulled, 0 skipped. 43.3 MB/s (898859 bytes in 0.020s)

**Comment by shakalaca** [comment]
Please kindly give it a try :)

**Comment by fusionneur** [comment]
proces.sh needs on line 40:
``while [[ $STATUS != 0 ]]``
instead of
``while [ $STATUS != 0 ]``
or else it will fail with error: /data/local/tmp/process.sh[52]: [: 0: unexpected operator/operand

**Comment by fusionneur** [comment]
I am not being able to create PR anymore

**Comment by fusionneur** [comment]
Created PR: https://github.com/shakalaca/MagiskOnEmulator/pull/9
